import Head from "next/head";
import Link from "next/link";
import React from "react";
import Footer from "./Footer";
import Header from "./Header";

const PageLayout = ({ children, title = "JB_DEV" }) => {
  return (
    <div className="container mx-auto p-4">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by JB" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <div className="flex justify-end p-4">
          <Header />
        </div>
        <main className="">{children}</main>
        <Footer />
      </div>
    </div>
  );
};

export default PageLayout;
